---
version: '3.7'
services:
  app:
    image: nginx
    init: true
    depends_on:
      - unity
    volumes:
      - .:/app
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${DOCKER_HOST_NGINX_PORT:-80}:80

  unity:
    build:
      context: .
      dockerfile: Docker/unity/Dockerfile
    init: true
    command: bash -c 'while :; do sleep 1; done'
    volumes:
      - .:/app
      - unity_assets:/root/unity-assets
      - unity_logs:/app/Logs/
      - unity_library:/app/Library/
      - unity_temp:/app/Temp/
      - unity_obj:/app/obj/
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      UNITY_PACKAGES_BUCKET: ${UNITY_PACKAGES_BUCKET}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}

volumes:
  unity_logs:
    driver: local
  unity_assets:
    driver: local
  unity_library:
    driver: local
  unity_temp:
    driver: local
  unity_obj:
    driver: local
